version: '3.8'

services:
  redis-dev:
    image: redis:6.2-alpine
    container_name: "redis-dev"
    ports:
      - "6388:6388"
    restart: always
    command: /bin/sh -c "redis-server --port $$REDISPORT --save 20 1 --loglevel warning --requirepass $$REDISPASSWORD"
    env_file:
      - .env
    volumes:
      - cache:/data

  fastapi:
    image: "fastapi-test"
    stop_signal: SIGINT
    build:
      context: .
    depends_on:
      - pg_database
    stdin_open: true
    command: >
      sh -c "poetry run python3 -m main"
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  cache: {}